---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-microservice
  labels:
    app: go-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-microservice
  template:
    metadata:
      labels:
        app: go-microservice
    spec:
      containers:
      - name: go-microservice
        image: go-microservice:0.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: go-microservice
spec:
  selector:
    app: go-microservice
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 8080
