package product

import (
	context "context"
	"log"
)

// implements RatingServer interface, generated by grpc
type RatingService struct{}

func (s *RatingService) GetRating(c context.Context, p *Product) (*Rating, error) {
	r, _ := ratingByProductId(p.Id)

	log.Printf("Returning rating for product id %s: %s", p.Id, r)

	return &Rating{Value: r}, nil
}
