on:
  push:
    tags:
      - 'v*'

name: Release

jobs:
  release:
    name: Release docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
      - name: get release version
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF/*tags\/v})
      - name: Publish to registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: rafaelportela/go-microservice
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "${{ env.RELEASE_VERSION }}"
